// <auto-generated />
namespace EscuelaTCSDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class grupo_persona_creado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(grupo_persona_creado));
        
        string IMigrationMetadata.Id
        {
            get { return "201906121353065_grupo_persona_creado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
