// <auto-generated />
namespace EscuelaTCSDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modalidad_objeto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modalidad_objeto));
        
        string IMigrationMetadata.Id
        {
            get { return "201906121536332_modalidad_objeto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
